Add support for blast chain
malik672/uniswap-sdk-core-rust pull request #64
Opened 2024-04-28 20:11 UTC by malik672

This pr aims to update the sdk-core by adding support for blast L2 chain

2024-04-29 07:37 UTC, shuhuiluo requested changes
Do a force push to clean the commit history.

2024-04-29 15:39 UTC, rustybera requested changes

2024-04-29 15:39 UTC, rustybera commented on Cargo.toml
> +version = "0.23.0"
0.22 wasn't used. Again, squash locally and force push.

2024-04-29 15:40 UTC, shuhuiluo requested changes

2024-04-29 15:40 UTC, shuhuiluo commented on Cargo.toml
> +version = "0.23.0"
0.22 wasn't used. Again, squash locally and force push.

2024-05-05 21:22 UTC, shuhuiluo approved these changes

2024-05-05 21:22 UTC, merged