new_hash
malik672/uniswap-sdk-core-rust pull request #66
Opened 2024-07-03 14:30 UTC by malik672

implement a faster hashmap
bump to 1.0.0

2024-07-05 23:20 UTC, shuhuiluo requested changes
Please fix linting.

2024-07-05 23:20 UTC, shuhuiluo commented on Cargo.toml
> +version = "1.0.0"
Let's not jump to 1.0.0 rn. I will have a PR updating dependencies.

2024-07-06 15:59 UTC, malik672 commented on Cargo.toml
> +version = "1.0.0"
ok

2024-07-07 22:04 UTC, shuhuiluo requested changes
Remove `missing_docs` attribute to fix linting.

2024-07-09 03:06 UTC, shuhuiluo requested changes

2024-07-09 03:06 UTC, shuhuiluo commented on Cargo.toml
> +version = "1.0.0"
```suggestion
version = "0.24.0"
```

2024-07-09 03:09 UTC, shuhuiluo approved these changes

2024-07-09 03:24 UTC, merged

2024-07-09 07:18 UTC, shuhuiluo commented
Please use squash merge to keep the main branch clean.