Update readme to make code example run.
malik672/uniswap-sdk-core-rust pull request #75
Opened 2024-07-24 08:04 UTC by cazeth

Hi, had to to make a couple updates to the code example in the readme to get it to run on my machine. Might have been something I did wrong, but this runs out of the box for me. Sharing in case it's useful.

2024-07-24 10:03 UTC, malik672 commented
ohh, make sense tbh

2024-07-25 04:56 UTC, shuhuiluo requested changes

2024-07-25 04:56 UTC, shuhuiluo commented on README.md
> +    let another_token = token!(CHAIN_ID, ANOTHER_TOKEN_ADDRESS, DECIMALS, "ETH", "Ethereum");
```suggestion
    let another_token = token!(
        CHAIN_ID,
        "0000000000000000000000000000000000000002",
        DECIMALS,
        "ETH",
        "Ethereum"
    );
```
`token!` can take either string literal or `&str`. If passing string literal to `address!` macro, "0x" should be stripped.

2024-07-25 04:56 UTC, shuhuiluo commented on README.md
> +use uniswap_sdk_core::token;
```suggestion
use crate::{prelude::*, token};
```

2024-07-25 09:48 UTC, shuhuiluo approved these changes
Thx.

2024-07-25 09:48 UTC, merged